### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Zudva** [xiumingzhang/mosculp-demo-ui#4]
Hi! Why i have this problem?

| => kivy main.py
[INFO   ] [Logger      ] Record log in /Applications/Kivy3.app/Contents/Resources/.kivy/logs/kivy_19-06-28_5.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.5 (default, Jun  1 2019, 17:33:32) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
[INFO   ] [Python      ] Interpreter at "/Applications/Kivy3.app/Contents/Resources/python"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "main.py", line 12, in <module>
     from app_config import app_name, clips, body_parts, part_mat, \
   File "/Users/Master/Downloads/Work/Python/Mosculp/mosculp-demo-ui-master/app_config.py", line 32, in <module>
     real2readable = {v: k for k, v in readable2real.iteritems()}
 AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by Zudva** [comment]
All ok. I must be use Kivy 2 and not compil kivy in pip.
